// Code generated by queryx, DO NOT EDIT.

package queryx

import (
	"strings"
)

type Config struct {
	URL string
}

func NewConfig(env string) *Config {
	switch env {
	case "development":
		return &Config{
			URL: fixURL("sqlite:blog_development.sqlite3"),
		}
	}
	return nil
}
func fixURL(rawURL string) string {
	return "file:" + strings.TrimPrefix(rawURL, "sqlite:")
}
