// Code generated by queryx, DO NOT EDIT.

package queryx

type PostChange struct {
	ID        BigInt
	Title     String
	Content   String
	CreatedAt Datetime
	UpdatedAt Datetime
}

func (c *PostChange) Changes() (columns []string, values []interface{}) {
	if c == nil {
		return columns, values
	}
	if c.ID.Set {
		columns = append(columns, "id")
		values = append(values, c.ID)
	}
	if c.Title.Set {
		columns = append(columns, "title")
		values = append(values, c.Title)
	}
	if c.Content.Set {
		columns = append(columns, "content")
		values = append(values, c.Content)
	}
	if c.CreatedAt.Set {
		columns = append(columns, "created_at")
		values = append(values, c.CreatedAt)
	}
	if c.UpdatedAt.Set {
		columns = append(columns, "updated_at")
		values = append(values, c.UpdatedAt)
	}
	return columns, values
}

func (c *PostChange) SetID(id int64) *PostChange {
	c.ID = NewBigInt(id)
	c.ID.Set = true
	return c
}

func (c *PostChange) SetTitle(title string) *PostChange {
	c.Title = NewString(title)
	c.Title.Set = true
	return c
}

func (c *PostChange) SetNullableTitle(title *string) *PostChange {
	c.Title = NewNullableString(title)
	c.Title.Set = true
	return c
}

func (c *PostChange) SetContent(content string) *PostChange {
	c.Content = NewString(content)
	c.Content.Set = true
	return c
}

func (c *PostChange) SetNullableContent(content *string) *PostChange {
	c.Content = NewNullableString(content)
	c.Content.Set = true
	return c
}

func (c *PostChange) SetCreatedAt(createdAt string) *PostChange {
	c.CreatedAt = NewDatetime(createdAt)
	c.CreatedAt.Set = true
	return c
}

func (c *PostChange) SetUpdatedAt(updatedAt string) *PostChange {
	c.UpdatedAt = NewDatetime(updatedAt)
	c.UpdatedAt.Set = true
	return c
}
