// Code generated by queryx, DO NOT EDIT.

import Database from "better-sqlite3";
import { Config } from "./config";

export class Adapter {
  private db: Database;

  constructor(config: Config) {
    this.db = new Database(config.url);
  }

  query<R>(query: string, ...args: any[]): R[] {
    console.log(query, args);
    let stmt = this.db.prepare(query);
    return stmt.all(...args) as R[];
  }

  queryOne<R>(query: string, ...args: any[]): R {
    console.log(query, args);
    let stmt = this.db.prepare(query);
    return stmt.get(...args) as R;
  }

  async exec(query: string, ...args: any[]) {}
}

export function rebind<T extends any[] = any[]>(query: string, args?: T) {}
