// Code generated by queryx, DO NOT EDIT.

package db

import (
	"database/sql"
	"errors"
	"fmt"

	"docker/db/queryx"
)

type PostQuery struct {
	adapter         *queryx.Adapter
	schema          *queryx.Schema
	queries         Queries
	selectStatement *queryx.SelectStatement
	preload         map[string]bool
	err             error
}

func NewPostQuery(adapter *queryx.Adapter, schema *queryx.Schema, queries Queries) *PostQuery {
	s := queryx.NewSelect().Select("posts.*").From("posts")
	return &PostQuery{
		adapter:         adapter,
		schema:          schema,
		queries:         queries,
		selectStatement: s,
		preload:         make(map[string]bool),
	}
}

func (q *PostQuery) Create(change *queryx.PostChange) (*Post, error) {
	if q.err != nil {
		return nil, q.err
	}

	record := &Post{
		schema:  q.schema,
		queries: q.queries,
	}
	now := queryx.Now("2006-01-02 15:04:05.000")
	if !change.CreatedAt.Set {
		change.SetCreatedAt(now)
	}
	if !change.UpdatedAt.Set {
		change.SetUpdatedAt(now)
	}
	columns, values := change.Changes()
	query, args := queryx.NewInsert().
		Into("posts").
		Columns(columns...).
		Values(values...).
		Returning("*").ToSQL()
	err := q.adapter.QueryOne(query, args...).Scan(record)
	if err != nil {
		return nil, err
	}

	return record, nil
}

func (q *PostQuery) InsertAll(changes []*queryx.PostChange) (int64, error) {
	if q.err != nil {
		return 0, q.err
	}

	if len(changes) == 0 {
		return 0, ErrInsertAllEmptyChanges
	}
	now := queryx.Now("2006-01-02 15:04:05.000")
	for _, change := range changes {
		if !change.CreatedAt.Set {
			change.SetCreatedAt(now)
		}
		if !change.UpdatedAt.Set {
			change.SetUpdatedAt(now)
		}
	}

	s := queryx.NewInsert().Into("posts")
	for i, change := range changes {
		columns, values := change.Changes()
		if i == 0 {
			s.Columns(columns...)
		}
		s.Values(values...)
	}

	query, args := s.ToSQL()
	return q.adapter.Exec(query, args...)
}

func (q *PostQuery) Delete(id int64) (int64, error) {
	query, args := queryx.NewDelete().From("posts").Where(q.schema.PostID.EQ(id)).ToSQL()
	result, err := q.adapter.Exec(query, args...)
	if err != nil {
		return 0, err
	}
	return result, err
}

func (q *PostQuery) Find(id int64) (*Post, error) {
	res, err := q.Where(q.schema.PostID.EQ(id)).First()
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, sql.ErrNoRows
	}
	res.schema = q.schema
	res.queries = q.queries
	return res, err
}

func (q *PostQuery) FindBy(where *queryx.Clause) (*Post, error) {
	return q.Where(where).First()
}

func (q *PostQuery) FindBySQL(query string, args ...interface{}) ([]*Post, error) {
	var postList []Post
	posts := make([]*Post, 0)
	err := q.adapter.Query(query, args...).Scan(&postList)
	if err != nil {
		return nil, err
	}
	for i := 0; i < len(postList); i++ {
		posts = append(posts, &postList[i])
	}
	return posts, nil
}

func (q *PostQuery) Where(clauses ...*queryx.Clause) *PostQuery {
	q.selectStatement.Where(clauses...)
	return q
}

func (q *PostQuery) Select(selection ...string) *PostQuery {
	q.selectStatement.Select(selection...)
	return q
}

func (q *PostQuery) Limit(limit int) *PostQuery {
	q.selectStatement.Limit(limit)
	return q
}

func (q *PostQuery) Offset(offset int) *PostQuery {
	q.selectStatement.Offset(offset)
	return q
}

func (q *PostQuery) Group(group string) *PostQuery {
	q.selectStatement.GroupBy(group)
	return q
}

func (q *PostQuery) Having(having string) *PostQuery {
	q.selectStatement.Having(having)
	return q
}

func (q *PostQuery) Joins(joins string) *PostQuery {
	q.selectStatement.Join(joins)
	return q
}

func (q *PostQuery) Order(order ...string) *PostQuery {
	q.selectStatement.Order(order...)
	return q
}

func (q *PostQuery) All() ([]*Post, error) {
	if q.err != nil {
		return nil, q.err
	}
	var rows []Post
	posts := make([]*Post, 0)
	query, args := q.selectStatement.ToSQL()
	err := q.adapter.Query(query, args...).Scan(&rows)
	if err != nil {
		return nil, err
	}

	if len(rows) == 0 {
		return posts, nil
	}

	for i := range rows {
		rows[i].schema = q.schema
		rows[i].queries = q.queries
		posts = append(posts, &rows[i])
	}

	return posts, nil
}

func (q *PostQuery) First() (*Post, error) {
	q.Limit(1)
	results, err := q.All()
	if err != nil {
		return nil, err
	}
	if len(results) > 0 {
		return results[0], nil
	}

	return nil, nil
}

func (q *PostQuery) Count() (int64, error) {
	var res struct {
		Count int64 `db:"count"`
	}
	q.selectStatement.Select("count(*)")
	query, args := q.selectStatement.ToSQL()
	if err := q.adapter.QueryOne(query, args...).Scan(&res); err != nil {
		return 0, err
	}

	return res.Count, nil
}

func (q *PostQuery) Avg(v string) (float64, error) {
	var res struct {
		Avg sql.NullFloat64 `db:"avg"`
	}
	q.selectStatement.Select(fmt.Sprintf("avg(%+v)", v))
	query, args := q.selectStatement.ToSQL()
	if err := q.adapter.QueryOne(query, args...).Scan(&res); err != nil {
		return 0, err
	}

	return res.Avg.Float64, nil
}

func (q *PostQuery) Sum(v string) (float64, error) {
	var res struct {
		Sum sql.NullFloat64 `db:"sum"`
	}
	q.selectStatement.Select(fmt.Sprintf("sum(%+v)", v))
	query, args := q.selectStatement.ToSQL()
	if err := q.adapter.QueryOne(query, args...).Scan(&res); err != nil {
		return 0, err
	}

	return res.Sum.Float64, nil
}

func (q *PostQuery) Max(v string) (float64, error) {
	var res struct {
		Max sql.NullFloat64 `db:"max"`
	}
	q.selectStatement.Select(fmt.Sprintf("max(%+v)", v))
	query, args := q.selectStatement.ToSQL()
	if err := q.adapter.QueryOne(query, args...).Scan(&res); err != nil {
		return 0, err
	}

	return res.Max.Float64, nil
}

func (q *PostQuery) Min(v string) (float64, error) {
	var res struct {
		Min sql.NullFloat64 `db:"min"`
	}
	q.selectStatement.Select(fmt.Sprintf("min(%+v)", v))
	query, args := q.selectStatement.ToSQL()
	if err := q.adapter.QueryOne(query, args...).Scan(&res); err != nil {
		return 0, err
	}

	return res.Min.Float64, nil
}

func (q *PostQuery) Exists() (bool, error) {
	q.selectStatement.Select("1 AS one").Limit(1)
	// select 1 as one from users limit 1
	query, args := q.selectStatement.ToSQL()
	var res struct {
		One int64 `db:"one"`
	}
	if err := q.adapter.QueryOne(query, args...).Scan(&res); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return false, nil
		}
		return false, err
	}

	return res.One == 1, nil
}

func (q *PostQuery) UpdateAll(change *queryx.PostChange) (int64, error) {
	if q.err != nil {
		return 0, q.err
	}
	now := queryx.Now("2006-01-02 15:04:05.000")
	if !change.UpdatedAt.Set {
		change.SetUpdatedAt(now)
	}
	columns, values := change.Changes()
	query, args := q.selectStatement.Update().Columns(columns...).Values(values...).ToSQL()
	result, err := q.adapter.Exec(query, args...)
	if err != nil {
		return 0, err
	}
	return result, err
}

func (q *PostQuery) DeleteAll() (int64, error) {
	query, args := q.selectStatement.Delete().ToSQL()
	result, err := q.adapter.Exec(query, args...)
	if err != nil {
		return 0, err
	}
	return result, err
}
