// Code generated by queryx, DO NOT EDIT.

package db

import (
	"fmt"
	"strings"

	"docker/db/queryx"
)

type Post struct {
	ID        int64           `json:"id" db:"id"`
	Title     queryx.String   `json:"title" db:"title"`
	Content   queryx.String   `json:"content" db:"content"`
	CreatedAt queryx.Datetime `json:"createdAt" db:"created_at"`
	UpdatedAt queryx.Datetime `json:"updatedAt" db:"updated_at"`

	schema  *queryx.Schema
	queries Queries
}

// String implements the stringer interface.
func (p *Post) String() string {
	var sb strings.Builder
	sb.WriteString("(Post ")
	sb.WriteString(fmt.Sprintf("id: %v", p.ID))
	sb.WriteString(", ")
	sb.WriteString(fmt.Sprintf("title: %s", p.Title))
	sb.WriteString(", ")
	sb.WriteString(fmt.Sprintf("content: %s", p.Content))
	sb.WriteString(", ")
	sb.WriteString(fmt.Sprintf("created_at: %v", p.CreatedAt))
	sb.WriteString(", ")
	sb.WriteString(fmt.Sprintf("updated_at: %v", p.UpdatedAt))
	sb.WriteString(")")
	return sb.String()
}

func (p *Post) applyChange(change *queryx.PostChange) error {
	if change == nil {
		return nil
	}
	if change.ID.Set {
		p.ID = change.ID.Val
	}
	if change.Title.Set {
		p.Title = change.Title
	}
	if change.Content.Set {
		p.Content = change.Content
	}
	if change.CreatedAt.Set {
		p.CreatedAt = change.CreatedAt
	}
	if change.UpdatedAt.Set {
		p.UpdatedAt = change.UpdatedAt
	}
	return nil
}
func (p *Post) Update(change *queryx.PostChange) error {
	_, err := p.queries.QueryPost().Where(p.schema.And(p.schema.PostID.EQ(p.ID))).UpdateAll(change)
	if err != nil {
		return err
	}

	return p.applyChange(change)
}

func (p *Post) Delete() error {
	_, err := p.queries.QueryPost().Delete(p.ID)
	return err
}
