// Code generated by queryx, DO NOT EDIT.

package queryx

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestNewBigInt(t *testing.T) {
	bi1 := NewBigInt(2)
	require.Equal(t, int64(2), bi1.Val)
	require.Equal(t, false, bi1.Null)

	bi2 := NewNullableBigInt(nil)
	require.Equal(t, true, bi2.Null)
}

func TestBigIntJSON(t *testing.T) {
	type Foo struct {
		X BigInt `json:"x"`
		Y BigInt `json:"y"`
	}
	x := NewBigInt(2)
	y := NewNullableBigInt(nil)
	s := `{"x":2,"y":null}`

	f1 := Foo{X: x, Y: y}
	b, err := json.Marshal(f1)
	require.NoError(t, err)
	require.Equal(t, s, string(b))

	var f2 Foo
	err = json.Unmarshal([]byte(s), &f2)
	require.NoError(t, err)
	require.Equal(t, x, f2.X)
	require.Equal(t, y, f2.Y)
}
