// Code generated by queryx, DO NOT EDIT.

package queryx

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
)

type BigInt struct {
	Val  int64
	Null bool
	Set  bool
}

func NewBigInt(v int64) BigInt {
	return BigInt{Val: v}
}

func NewNullableBigInt(v *int64) BigInt {
	if v != nil {
		return NewBigInt(*v)
	}
	return BigInt{Null: true}
}

// Scan implements the Scanner interface.
func (bi *BigInt) Scan(value interface{}) error {
	n := sql.NullInt64{}
	err := n.Scan(value)
	if err != nil {
		return err
	}
	bi.Val, bi.Null = n.Int64, !n.Valid
	return nil
}

// Value implements the driver Valuer interface.
func (bi BigInt) Value() (driver.Value, error) {
	if bi.Null {
		return nil, nil
	}
	return bi.Val, nil
}

func (bi BigInt) MarshalJSON() ([]byte, error) {
	if bi.Null {
		return json.Marshal(nil)
	}
	return json.Marshal(bi.Val)
}

func (bi *BigInt) UnmarshalJSON(b []byte) error {
	if string(b) == "null" {
		bi.Null = true
		return nil
	}
	if err := json.Unmarshal(b, &bi.Val); err != nil {
		return err
	}
	return nil
}
