// Code generated by queryx, DO NOT EDIT.

package queryx

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestNewBigInt(t *testing.T) {
	i := NewBigInt(2)
	require.Equal(t, int64(2), i.Val)
	require.Equal(t, false, i.Null)
}

func TestNewNullableBigInt(t *testing.T) {
	i := NewNullableBigInt(nil)
	require.Equal(t, true, i.Null)
}
