// Code generated by queryx, DO NOT EDIT.

package queryx

import "fmt"

type BooleanColumn struct {
	Name  string
	Table *Table
}

func (t *Table) NewBooleanColumn(name string) *BooleanColumn {
	return &BooleanColumn{
		Table: t,
		Name:  name,
	}
}

func (c *BooleanColumn) EQ(v bool) *Clause {
	return &Clause{
		fragment: fmt.Sprintf("%s.%s = ?", c.Table.Name, c.Name),
		args:     []interface{}{v},
	}
}

func (c *BooleanColumn) NE(v bool) *Clause {
	return &Clause{
		fragment: fmt.Sprintf("%s.%s <> ?", c.Table.Name, c.Name),
		args:     []interface{}{v},
	}
}
