// Code generated by queryx, DO NOT EDIT.

package queryx

import (
	"database/sql"
	"database/sql/driver"
	"time"
)

type Datetime struct {
	Val  time.Time
	Null bool
	Set  bool
}

func parseDatetime(s string) (*time.Time, error) {
	// TODO: timezone from config
	location, err := time.LoadLocation("Asia/Shanghai")
	if err != nil {
		return nil, err
	}
	t, err := time.ParseInLocation("2006-01-02 15:04:05", s, location)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func NewDatetime(v string) Datetime {
	t, err := parseDatetime(v)
	if err != nil {
		return Datetime{Null: true}
	}
	return Datetime{Val: t.UTC()}
}

func NewNullableDatetime(v *string) Datetime {
	if v != nil {
		return NewDatetime(*v)
	}
	return Datetime{Null: true}
}

// TODO:
func (d Datetime) Format(layout string) string {
	return ""
}

// Scan implements the Scanner interface.
// TODO:
func (d *Datetime) Scan(value interface{}) error {
	n := sql.NullTime{}
	err := n.Scan(value)
	if err != nil {
		return err
	}
	d.Val, d.Null = n.Time, !n.Valid
	return nil
}

// Value implements the driver Valuer interface.
func (d Datetime) Value() (driver.Value, error) {
	if d.Null {
		return nil, nil
	}
	return d.Val.UTC(), nil
}

func (d Datetime) MarshalJSON() ([]byte, error) {
	return nil, nil
}

func (d *Datetime) UnmarshalJSON(text []byte) error {
	return nil
}
