// Code generated by queryx, DO NOT EDIT.

package queryx

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestNewDate(t *testing.T) {
	i := NewDate("2012-12-12")
	require.Equal(t, "2012-12-12", i.Val.Local().Format("2006-01-02"))
	require.Equal(t, false, i.Null)
}

func TestNewNullableDate(t *testing.T) {
	i := NewNullableDate(nil)
	require.Equal(t, true, i.Null)
}
