// Code generated by queryx, DO NOT EDIT.

package queryx

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestNewFloat(t *testing.T) {
	i := NewFloat(2.1)
	require.Equal(t, 2.1, i.Val)
	require.Equal(t, false, i.Null)
}

func TestNewNullableFloat(t *testing.T) {
	i := NewNullableFloat(nil)
	require.Equal(t, true, i.Null)
}
