// Code generated by queryx, DO NOT EDIT.

package queryx

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestNewInteger(t *testing.T) {
	i := NewInteger(2)
	require.Equal(t, int32(2), i.Val)
	require.Equal(t, false, i.Null)
}

func TestNewNullableInteger(t *testing.T) {
	i := NewNullableInteger(nil)
	require.Equal(t, true, i.Null)
}
