// Code generated by queryx, DO NOT EDIT.

package queryx

import (
	"fmt"
)

type JSONColumn struct {
	Name  string
	Table *Table
}

func (t *Table) NewJSONColumn(name string) *JSONColumn {
	return &JSONColumn{
		Table: t,
		Name:  name,
	}
}

func (c *JSONColumn) IsNull() *Clause {
	return &Clause{
		fragment: fmt.Sprintf("%s.%s is null", c.Table.Name, c.Name),
	}
}

func (c *JSONColumn) NotNull() *Clause {
	return &Clause{
		fragment: fmt.Sprintf("%s.%s is not null", c.Table.Name, c.Name),
	}
}
