// Code generated by queryx, DO NOT EDIT.

package queryx

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

type JSON struct {
	Val  map[string]interface{}
	Null bool
	Set  bool
}

func NewJSON(v map[string]interface{}) JSON {
	return JSON{Val: v}
}

func NewNullableJSON(v interface{}) JSON {
	if v != nil {
		return NewJSON(v.(map[string]interface{}))
	}
	return JSON{Null: true}
}

// Scan implements the Scanner interface.
func (j *JSON) Scan(value interface{}) error {
	if value == nil {
		j.Val, j.Null = nil, true
		return nil
	}
	b, ok := value.([]byte)
	if !ok {
		return fmt.Errorf("JSON scan source was not []byte")
	}
	return json.Unmarshal(b, &j.Val)
}

// Value implements the driver Valuer interface.
func (j JSON) Value() (driver.Value, error) {
	return json.Marshal(j.Val)
}

func (j JSON) MarshalJSON() ([]byte, error) {
	return nil, nil
}

func (j *JSON) UnmarshalJSON(b []byte) error {
	return nil
}
