// Code generated by queryx, DO NOT EDIT.

package queryx

type StringArrayColumn struct {
	Name  string
	Table *Table
}

func (t *Table) NewStringArrayColumn(name string) *StringArrayColumn {
	return &StringArrayColumn{
		Table: t,
		Name:  name,
	}
}
