// Code generated by queryx, DO NOT EDIT.

package queryx

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestNewString(t *testing.T) {
	i := NewString("queryx")
	require.Equal(t, "queryx", i.Val)
	require.Equal(t, false, i.Null)
}

func TestNewNullableString(t *testing.T) {
	i := NewNullableString(nil)
	require.Equal(t, true, i.Null)
}
