// Code generated by queryx, DO NOT EDIT.

package queryx

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestNewString(t *testing.T) {
	i := NewString("queryx")
	require.Equal(t, "queryx", i.Val)
	require.Equal(t, false, i.Null)
}

func TestNewNullableString(t *testing.T) {
	i := NewNullableString(nil)
	require.Equal(t, true, i.Null)
}

func TestStringMarshalJSON(t *testing.T) {
	i := NewString("queryx")
	require.Equal(t, "queryx", i.Val)
	require.Equal(t, false, i.Null)
	_, err := i.MarshalJSON()
	require.NoError(t, err)
}

func TestStringUnmarshalJSON(t *testing.T) {
	i := NewString("queryx")
	require.Equal(t, "queryx", i.Val)
	require.Equal(t, false, i.Null)
	bytes, err := i.MarshalJSON()
	require.NoError(t, err)
	s := NewString("")
	err = s.UnmarshalJSON(bytes)
	require.NoError(t, err)
	require.Equal(t, "queryx", s.Val)
	require.Equal(t, false, s.Null)
}

func TestStringScan(t *testing.T) {
	i := NewString("queryx")
	require.Equal(t, "queryx", i.Val)
	require.Equal(t, false, i.Null)
	err := i.Scan("query")
	require.NoError(t, err)
	require.Equal(t, "query", i.Val)
}

func TestStringValue(t *testing.T) {
	i := NewString("queryx")
	require.Equal(t, "queryx", i.Val)
	require.Equal(t, false, i.Null)
	value, err := i.Value()
	require.NoError(t, err)
	require.Equal(t, "queryx", value)
}
