// Code generated by queryx, DO NOT EDIT.

package queryx

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

type String struct {
	Val  string
	Null bool
	Set  bool
}

func NewString(v string) String {
	return String{Val: v, Set: true}
}

func NewNullableString(v *string) String {
	if v != nil {
		return NewString(*v)
	}
	return String{Null: true, Set: true}
}

// Scan implements the Scanner interface.
func (s *String) Scan(value interface{}) error {
	ns := sql.NullString{String: s.Val}
	err := ns.Scan(value)
	s.Val, s.Null = ns.String, !ns.Valid
	return err
}

// Value implements the driver Valuer interface.
func (s String) Value() (driver.Value, error) {
	if s.Null {
		return nil, nil
	}
	return s.Val, nil
}

// MarshalJSON implements the json.Marshaler interface.
func (s String) MarshalJSON() ([]byte, error) {
	if s.Null {
		return json.Marshal(nil)
	}
	return json.Marshal(s.Val)
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (s *String) UnmarshalJSON(data []byte) error {
	s.Set = true
	if string(data) == "null" {
		s.Null = true
		return nil
	}
	if err := json.Unmarshal(data, &s.Val); err != nil {
		return err
	}
	return nil
}

// String implements the stringer interface.
func (s String) String() string {
	if s.Null {
		return "null"
	}
	return fmt.Sprintf(`"%s"`, s.Val)
}
