// Code generated by queryx, DO NOT EDIT.

package queryx

import (
	"database/sql/driver"
	"encoding/json"
	"time"
)

type Time struct {
	Val  time.Time
	Null bool
	Set  bool
}

// TODO:
func NewTime(v string) Time {
	return Time{}
}

// TODO:
func NewNullableTime(v *string) Time {
	return Time{Null: true}
}

// Scan implements the Scanner interface.
func (t *Time) Scan(value interface{}) error {
	return nil
}

// Value implements the driver Valuer interface.
func (t Time) Value() (driver.Value, error) {
	return nil, nil
}

func (t Time) MarshalJSON() ([]byte, error) {
	if t.Null {
		return json.Marshal(nil)
	}
	return json.Marshal(t.Val)
}

func (t *Time) UnmarshalJSON(text []byte) error {
	return nil
}
