// Code generated by queryx, DO NOT EDIT.

package queryx

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestNewTime(t *testing.T) {
	i := NewTime("12:12:12")
	require.Equal(t, "12:12:12", i.Val.Local().Format("15:04:05"))
	require.Equal(t, false, i.Null)
}

func TestNewNullableTime(t *testing.T) {
	i := NewNullableTime(nil)
	require.Equal(t, true, i.Null)
}
