// Code generated by queryx, DO NOT EDIT.

package queryx

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
)

type UUID struct {
	Val   string
	Valid bool
	Set   bool
}

func NewUUID(v string) UUID {
	return UUID{Val: v, Valid: true, Set: true}
}

func NewNullableUUID(v *string) UUID {
	if v != nil {
		return NewUUID(*v)
	}
	return UUID{Set: true}
}

// Scan implements the Scanner interface.
func (u *UUID) Scan(value interface{}) error {
	ns := sql.NullString{String: u.Val}
	err := ns.Scan(value)
	u.Val, u.Valid = ns.String, ns.Valid
	return err
}

// Value implements the driver Valuer interface.
func (u UUID) Value() (driver.Value, error) {
	if !u.Valid {
		return nil, nil
	}
	return u.Val, nil
}

// MarshalJSON implements the json.Marshaler interface.
func (u UUID) MarshalJSON() ([]byte, error) {
	if !u.Valid {
		return json.Marshal(nil)
	}
	return json.Marshal(u.Val)
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (u *UUID) UnmarshalJSON(data []byte) error {
	u.Set = true
	if string(data) == "null" {
		return nil
	}
	u.Valid = true
	if err := json.Unmarshal(data, &u.Val); err != nil {
		return err
	}
	return nil
}

// String implements the stringer interface.
func (u UUID) String() string {
	if !u.Valid {
		return "null"
	}
	return u.Val
}
